version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: first_container
    env_file:
      - .env
    ports:
      - "$(POSTGRES_PORT:-5432):5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
